# Generated by Django 5.0.2 on 2024-05-01 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherUpdate', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
